### ISSUE TITLE
setuptools refactor?

### ISSUE THREAD

**Issue by lmmarsano** [wrsexton/learn2spell#1]
`setup.py` is reading `requirements.txt`

https://github.com/wrsexton/learn2spell/blob/084daca53a0764e98e7e6ce1658f6f9da5213a23/setup.py#L5-L6

That was a hack around the way Michael codes.
Instead of doing that, we can simplify
```python
#!/usr/bin/env python
import setuptools as ST
ST.setup()
```
and [list requirements in `setup.cfg` like this](https://dev.azure.com/humana/DevOps/_git/ALM.MessageRouter?path=%2Fsetup.cfg&version=GBmaster&line=13&lineEnd=20&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents).

Then we don't need `requirements.txt` at all.
`requirements.txt` is meant for pinning exact versions for reproducible builds, so to do that, we can do `pip freeze >requirements.txt` as conventionally done.

As a bonus, that simplifies `Makefile`, too, from
https://github.com/wrsexton/learn2spell/blob/084daca53a0764e98e7e6ce1658f6f9da5213a23/Makefile#L20
to
```Makefile
.setup: setup.cfg
```

**Comment by wrsexton** [comment]
Wow, I had no idea!  Thanks Luis, it's crazy how much hacking we've had to do around code that isn't even that old lol.  I wonder what other misconceptions I have that I've yet to uncover.  😂 

I've linked a PR to this issue and invited you to collaborate, so I can add you as a reviewer!
